spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.40.187.86:3306/meeting?characterEncoding=utf8&autoReconnect=true&connectTimeout=60000&socketTimeout=130000&useSSL=false&serverTimezone=UTC&useUnicode=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 161718
  redis:
    database: 0
    host: 121.40.187.86
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 -1 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: '161718'
    port: 6379
  mail:
    host: smtp.163.com
    username: stosjw@163.com
    password: EDYZENBXTUGEOELS
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true